services:
  mysql:
    image: mysql:8.0
    container_name: caretriage-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_prod_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - caretriage-net

  backend:
    build: ./code/backend/backend
    container_name: caretriage-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DB_NAME: caretriage
      DB_USERNAME: linhtranne
      DB_PASSWORD: 123456
      JWT_SECRET: ${JWT_SECRET:-caretriage-docker-secret-key-min-256-bits-long-for-hmac-sha256}
      AI_SERVICE_URL: http://ai-service:8000
      AI_SERVICE_INTERNAL_KEY: ${INTERNAL_API_KEY}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - caretriage-net

  ai-service:
    image: ${DOCKER_USERNAME}/caretriage-ai:latest
    container_name: caretriage-ai-prod
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL_NAME: ${GEMINI_MODEL_NAME}
      GEMINI_EMBEDDING_MODEL: ${GEMINI_EMBEDDING_MODEL}
      GEMINI_TEMPERATURE: ${GEMINI_TEMPERATURE}
      GEMINI_TOP_P: ${GEMINI_TOP_P}
      GEMINI_MAX_TOKENS: ${GEMINI_MAX_TOKENS}
      INTERNAL_API_KEY: ${INTERNAL_API_KEY}
      MAX_BODY_SIZE_BYTES: ${MAX_BODY_SIZE_BYTES}
      ENTREZ_EMAIL: ${ENTREZ_EMAIL}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      CHROMA_DB_PATH: ${CHROMA_DB_PATH}
    networks:
      - caretriage-net

  frontend:
    image: ${DOCKER_USERNAME}/caretriage-frontend:latest
    container_name: caretriage-frontend-prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - caretriage-net

  admin-frontend:
    image: ${DOCKER_USERNAME}/caretriage-admin:latest
    container_name: caretriage-admin-prod
    restart: unless-stopped
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - caretriage-net

volumes:
  mysql_prod_data:

networks:
  caretriage-net:
    driver: bridge
