export const DOCTOR_COPY_KEYS = {
  pageTitle: 'doctorReview.pageTitle',
  queue: {
    title: 'doctorReview.queue.title',
    filters: {
      all: 'doctorReview.queue.filters.all',
      urgent: 'doctorReview.queue.filters.urgent',
      new: 'doctorReview.queue.filters.new',
      pending: 'doctorReview.queue.filters.pending',
    },
  },
  summary: {
    title: 'doctorReview.summary.title',
    chiefComplaint: 'doctorReview.summary.chiefComplaint',
    duration: 'doctorReview.summary.duration',
    severity: 'doctorReview.summary.severity',
    aiDepartment: 'doctorReview.summary.aiDepartment',
    viewDetails: 'doctorReview.summary.viewDetails',
    sampleComplaint: 'doctorReview.summary.sampleComplaint',
    sampleDurationSeverity: 'doctorReview.summary.sampleDurationSeverity',
    sampleDepartment: 'doctorReview.summary.sampleDepartment',
  },
  ehr: {
    title: 'doctorReview.ehr.title',
    categories: {
      symptom: 'doctorReview.ehr.categories.symptom',
      duration: 'doctorReview.ehr.categories.duration',
      medication: 'doctorReview.ehr.categories.medication',
      allergy: 'doctorReview.ehr.categories.allergy',
      vital: 'doctorReview.ehr.categories.vital',
      condition: 'doctorReview.ehr.categories.condition',
    },
  },
  timeline: {
    title: 'doctorReview.timeline.title',
    viewFull: 'doctorReview.timeline.viewFull',
    aiLabel: 'doctorReview.timeline.aiLabel',
    patientLabel: 'doctorReview.timeline.patientLabel',
    sampleAiMessage: 'doctorReview.timeline.sampleAiMessage',
    samplePatientMessage: 'doctorReview.timeline.samplePatientMessage',
  },
  missingInfo: {
    title: 'doctorReview.missingInfo.title',
    familyHistory: 'doctorReview.missingInfo.familyHistory',
    medications: 'doctorReview.missingInfo.medications',
  },
  actions: {
    approve: 'doctorReview.actions.approve',
    override: 'doctorReview.actions.override',
    requestInfo: 'doctorReview.actions.requestInfo',
    assignDepartment: 'doctorReview.actions.assignDepartment',
    convertToNote: 'doctorReview.actions.convertToNote',
    form: {
      department: 'doctorReview.actions.form.department',
      selectDepartment: 'doctorReview.actions.form.selectDepartment',
      messageToPatient: 'doctorReview.actions.form.messageToPatient',
      overrideNote: 'doctorReview.actions.form.overrideNote',
      whatInfo: 'doctorReview.actions.form.whatInfo',
      reasonOverride: 'doctorReview.actions.form.reasonOverride',
      submit: 'doctorReview.actions.form.submit',
      cancel: 'doctorReview.actions.form.cancel',
      actionFailed: 'doctorReview.actions.form.actionFailed',
      approving: 'doctorReview.actions.form.approving',
    }
  },
  queueSamples: {
    patientOneName: 'doctorReview.queueSamples.patientOneName',
    patientOneComplaint: 'doctorReview.queueSamples.patientOneComplaint',
    patientOneTime: 'doctorReview.queueSamples.patientOneTime',
    patientTwoName: 'doctorReview.queueSamples.patientTwoName',
    patientTwoComplaint: 'doctorReview.queueSamples.patientTwoComplaint',
    patientTwoTime: 'doctorReview.queueSamples.patientTwoTime',
    patientThreeName: 'doctorReview.queueSamples.patientThreeName',
    patientThreeComplaint: 'doctorReview.queueSamples.patientThreeComplaint',
    patientThreeTime: 'doctorReview.queueSamples.patientThreeTime',
  },
} as const
