export const DOCTOR_APPOINTMENT_TABS = {
  TODAY: 0,
  NEW_REQUESTS: 1,
  IN_PROGRESS: 2,
  COMPLETED: 3,
  ALL: 4,
} as const

export const DOCTOR_APPOINTMENT_KEYS = {
  pageTitle: 'doctorAppointments.pageTitle',
  badge: 'doctorAppointments.badge',
  refresh: 'doctorAppointments.refresh',
  searchPlaceholder: 'doctorAppointments.searchPlaceholder',
  emptyTitle: 'doctorAppointments.emptyTitle',
  emptyDescription: 'doctorAppointments.emptyDescription',
  loadingList: 'doctorAppointments.loadingList',
  loadError: 'doctorAppointments.loadError',
  updateSuccess: 'doctorAppointments.updateSuccess',
  updateError: 'doctorAppointments.updateError',
  table: {
    time: 'doctorAppointments.table.time',
    patient: 'doctorAppointments.table.patient',
    reason: 'doctorAppointments.table.reason',
    status: 'doctorAppointments.table.status',
    actions: 'doctorAppointments.table.actions',
    triageTicket: 'doctorAppointments.table.triageTicket',
    identifierPrefix: 'doctorAppointments.table.identifierPrefix',
  },
  tabs: {
    today: 'doctorAppointments.tabs.today',
    newRequests: 'doctorAppointments.tabs.newRequests',
    inProgress: 'doctorAppointments.tabs.inProgress',
    completed: 'doctorAppointments.tabs.completed',
    all: 'doctorAppointments.tabs.all',
  },
  actions: {
    detail: 'doctorAppointments.actions.detail',
    confirm: 'doctorAppointments.actions.confirm',
    start: 'doctorAppointments.actions.start',
    complete: 'doctorAppointments.actions.complete',
    createRecord: 'doctorAppointments.actions.createRecord',
    markNoShow: 'doctorAppointments.actions.markNoShow',
    close: 'doctorAppointments.actions.close',
    confirmAction: 'doctorAppointments.actions.confirmAction',
  },
  dialog: {
    inProgress: 'doctorAppointments.dialog.inProgress',
    completed: 'doctorAppointments.dialog.completed',
    cancelled: 'doctorAppointments.dialog.cancelled',
    confirmed: 'doctorAppointments.dialog.confirmed',
    noShow: 'doctorAppointments.dialog.noShow',
    cancelledReasonLabel: 'doctorAppointments.dialog.cancelledReasonLabel',
    noteLabel: 'doctorAppointments.dialog.noteLabel',
    cancelledReasonPlaceholder: 'doctorAppointments.dialog.cancelledReasonPlaceholder',
    notePlaceholder: 'doctorAppointments.dialog.notePlaceholder',
    patientMessage: 'doctorAppointments.dialog.patientMessage',
    notePrefix: 'doctorAppointments.dialog.notePrefix',
  },
  status: {
    pending: 'doctorAppointments.status.pending',
    confirmed: 'doctorAppointments.status.confirmed',
    inProgress: 'doctorAppointments.status.inProgress',
    completed: 'doctorAppointments.status.completed',
    cancelled: 'doctorAppointments.status.cancelled',
    noShow: 'doctorAppointments.status.noShow',
  },
  fallback: {
    time: 'doctorAppointments.fallback.time',
    missingPhone: 'doctorAppointments.fallback.missingPhone',
    unknownReason: 'doctorAppointments.fallback.unknownReason',
  },
} as const

export const DOCTOR_APPOINTMENT_UI = {
  refreshIconSize: 18,
  chipIconSize: 14,
  smallIconSize: 16,
  statusDialogRows: 4,
  previewClampLines: 2,
  progressSize: 42,
  progressThickness: 5,
  avatarSize: 48,
  detailAvatarSize: 64,
  tableMinWidth: 1000,
  tabMinHeight: 48,
  tabMinWidth: 120,
  searchWidth: 320,
  detailDrawerWidth: 480,
  noteIconOffset: 4,
  tableSpacingY: 12,
  timeSubstringStart: 0,
  timeSubstringEnd: 5,
  dateDialogPadding: 3,
  emptyIconSize: 64,
} as const
