export const DOCTOR_PATIENTS_KEYS = {
  pageTitle: 'doctorPatients.pageTitle',
  subtitle: 'doctorPatients.subtitle',
  searchPlaceholder: 'doctorPatients.searchPlaceholder',
  sourceFilterLabel: 'doctorPatients.sourceFilterLabel',
  ticketStatusLabel: 'doctorPatients.ticketStatusLabel',
  allStatuses: 'doctorPatients.allStatuses',
  loadingDetail: 'doctorPatients.loadingDetail',
  loadError: 'doctorPatients.loadError',
  detailError: 'doctorPatients.detailError',
  table: {
    patient: 'doctorPatients.table.patient',
    ageGender: 'doctorPatients.table.ageGender',
    relationshipSource: 'doctorPatients.table.relationshipSource',
    lastInteraction: 'doctorPatients.table.lastInteraction',
    nextAppointment: 'doctorPatients.table.nextAppointment',
    latestTicketStatus: 'doctorPatients.table.latestTicketStatus',
    actions: 'doctorPatients.table.actions',
  },
  source: {
    appointment: 'doctorPatients.source.appointment',
    medicalRecord: 'doctorPatients.source.medicalRecord',
    triageTicket: 'doctorPatients.source.triageTicket',
    unknown: 'doctorPatients.source.unknown',
  },
  gender: {
    male: 'doctorPatients.gender.male',
    female: 'doctorPatients.gender.female',
    other: 'doctorPatients.gender.other',
    missingAge: 'doctorPatients.gender.missingAge',
    ageSuffix: 'doctorPatients.gender.ageSuffix',
    separator: 'doctorPatients.gender.separator',
  },
  latestTicketStatus: {
    none: 'doctorPatients.latestTicketStatus.none',
    NEW: 'doctorPatients.latestTicketStatus.NEW',
    IN_TRIAGE: 'doctorPatients.latestTicketStatus.IN_TRIAGE',
    TRIAGED: 'doctorPatients.latestTicketStatus.TRIAGED',
    CLOSED: 'doctorPatients.latestTicketStatus.CLOSED',
    REJECTED: 'doctorPatients.latestTicketStatus.REJECTED',
  },
  relationshipFilter: {
    all: 'doctorPatients.relationshipFilter.all',
    appointment: 'doctorPatients.relationshipFilter.appointment',
    medicalRecord: 'doctorPatients.relationshipFilter.medicalRecord',
    triageTicket: 'doctorPatients.relationshipFilter.triageTicket',
  },
  kpi: {
    all: 'doctorPatients.kpi.all',
    upcoming: 'doctorPatients.kpi.upcoming',
    records: 'doctorPatients.kpi.records',
    triage: 'doctorPatients.kpi.triage',
  },
  details: {
    overview: 'doctorPatients.details.overview',
    appointments: 'doctorPatients.details.appointments',
    records: 'doctorPatients.details.records',
    tickets: 'doctorPatients.details.tickets',
    identifierPrefix: 'doctorPatients.details.identifierPrefix',
    identifierSeparator: 'doctorPatients.details.identifierSeparator',
    adminInfo: 'doctorPatients.details.adminInfo',
    clinicalInfo: 'doctorPatients.details.clinicalInfo',
    fullName: 'doctorPatients.details.fullName',
    email: 'doctorPatients.details.email',
    phone: 'doctorPatients.details.phone',
    address: 'doctorPatients.details.address',
    bloodType: 'doctorPatients.details.bloodType',
    insurance: 'doctorPatients.details.insurance',
    allergies: 'doctorPatients.details.allergies',
    chronicConditions: 'doctorPatients.details.chronicConditions',
    emergencyContact: 'doctorPatients.details.emergencyContact',
    noValue: 'doctorPatients.details.noValue',
    unknownBloodType: 'doctorPatients.details.unknownBloodType',
    noInsurance: 'doctorPatients.details.noInsurance',
    noAllergy: 'doctorPatients.details.noAllergy',
    noChronicCondition: 'doctorPatients.details.noChronicCondition',
    noEmergencyContact: 'doctorPatients.details.noEmergencyContact',
  },
} as const

export const DOCTOR_PATIENTS_UI = {
  debounceMs: 400,
  firstPage: 0,
  countProbeSize: 1,
  defaultPageSize: 10,
  kpiAvatarAlpha: 0.12,
  pageSizeOptions: [5, 10, 20],
  detailTabs: {
    overview: 0,
    appointments: 1,
    records: 2,
    tickets: 3,
  },
  dataGridHeights: {
    row: 112,
    columnHeader: 64,
    panel: 720,
  },
  detailDrawerWidths: {
    sm: 580,
    md: 740,
  },
} as const
