export const EHR_KEYS = {
  navigation: {
    upload: '/doctor/ehr/upload',
    search: '/doctor/ehr/search',
    resultBase: '/doctor/ehr/result',
    summaryBase: '/doctor/ehr/summary',
  },
  common: {
    retry: 'ehr.common.retry',
    reset: 'ehr.common.reset',
    percentSuffix: 'ehr.common.percentSuffix',
    patientIdentifierPrefix: 'ehr.common.patientIdentifierPrefix',
    aiResultTitle: 'ehr.common.aiResultTitle',
    extractedTitle: 'ehr.common.extractedTitle',
    originalTextTitle: 'ehr.common.originalTextTitle',
    unknownDate: 'ehr.common.unknownDate',
    noValue: 'ehr.common.noValue',
  },
  upload: {
    title: 'ehr.upload.title',
    subtitle: 'ehr.upload.subtitle',
    textTab: 'ehr.upload.textTab',
    fileTab: 'ehr.upload.fileTab',
    submit: 'ehr.upload.submit',
    processing: 'ehr.upload.processing',
    active: 'ehr.upload.active',
    textPlaceholder: 'ehr.upload.textPlaceholder',
    fileRequired: 'ehr.upload.fileRequired',
    fileTypeError: 'ehr.upload.fileTypeError',
    fileSizeError: 'ehr.upload.fileSizeError',
    fileReadError: 'ehr.upload.fileReadError',
    serverError: 'ehr.upload.serverError',
    noteIdError: 'ehr.upload.noteIdError',
    noteTypeRequired: 'ehr.upload.noteTypeRequired',
    patientIdLabel: 'ehr.upload.patientIdLabel',
    noteTypeLabel: 'ehr.upload.noteTypeLabel',
    patientIdTypeError: 'ehr.upload.patientIdTypeError',
    patientIdRequired: 'ehr.upload.patientIdRequired',
    patientIdPositive: 'ehr.upload.patientIdPositive',
    patientIdInteger: 'ehr.upload.patientIdInteger',
    textRequired: 'ehr.upload.textRequired',
    textMinLength: 'ehr.upload.textMinLength',
    noteTypes: {
      ADMISSION: 'ehr.upload.noteTypes.ADMISSION',
      PROGRESS: 'ehr.upload.noteTypes.PROGRESS',
      DISCHARGE: 'ehr.upload.noteTypes.DISCHARGE',
      CONSULTATION: 'ehr.upload.noteTypes.CONSULTATION',
      PRESCRIPTION: 'ehr.upload.noteTypes.PRESCRIPTION',
    },
  },
  search: {
    title: 'ehr.search.title',
    subtitle: 'ehr.search.subtitle',
    validation: 'ehr.search.validation',
    searchError: 'ehr.search.searchError',
    symptom: 'ehr.search.symptom',
    symptomPlaceholder: 'ehr.search.symptomPlaceholder',
    medication: 'ehr.search.medication',
    medicationPlaceholder: 'ehr.search.medicationPlaceholder',
    condition: 'ehr.search.condition',
    conditionPlaceholder: 'ehr.search.conditionPlaceholder',
    dateFrom: 'ehr.search.dateFrom',
    dateTo: 'ehr.search.dateTo',
    severity: 'ehr.search.severity',
    viewEhr: 'ehr.search.viewEhr',
    submit: 'ehr.search.submit',
    columns: {
      patient: 'ehr.search.columns.patient',
      email: 'ehr.search.columns.email',
      totalNotes: 'ehr.search.columns.totalNotes',
      findings: 'ehr.search.columns.findings',
      actions: 'ehr.search.columns.actions',
    },
    severityOptions: {
      all: 'ehr.search.severityOptions.all',
      mild: 'ehr.search.severityOptions.mild',
      moderate: 'ehr.search.severityOptions.moderate',
      severe: 'ehr.search.severityOptions.severe',
    },
  },
  result: {
    loadError: 'ehr.result.loadError',
    listLabel: 'ehr.result.listLabel',
    confidencePrefix: 'ehr.result.confidencePrefix',
    downloadPdf: 'ehr.result.downloadPdf',
    history: 'ehr.result.history',
  },
  summary: {
    titlePrefix: 'ehr.summary.titlePrefix',
    loadingTitle: 'ehr.summary.loadingTitle',
    loadingSubtitle: 'ehr.summary.loadingSubtitle',
    errorSubtitle: 'ehr.summary.errorSubtitle',
    loadError: 'ehr.summary.loadError',
    searchBack: 'ehr.summary.searchBack',
    pageTitle: 'ehr.summary.pageTitle',
    overviewSubtitle: 'ehr.summary.overviewSubtitle',
    newNote: 'ehr.summary.newNote',
    clinicalHistory: 'ehr.summary.clinicalHistory',
    noNotes: 'ehr.summary.noNotes',
    entityLoadError: 'ehr.summary.entityLoadError',
    entityCountSuffix: 'ehr.summary.entityCountSuffix',
  },
} as const

export const EHR_UI = {
  validationTextMinLength: 10,
  maxUploadSizeBytes: 20 * 1024 * 1024,
  previewEntityCount: 2,
  fullPercent: 100,
  successConfidenceThreshold: 80,
  summaryAccordionRadiusMultiplier: 4,
  searchPageSizeOptions: [5, 10, 20],
  skeletonCards: [1, 2, 3],
} as const
