sonar.projectKey=caretriage-backend
sonar.projectName=CareTriage Backend
sonar.projectVersion=1.0

# Path to sources
sonar.sources=src/main/java

# Path to tests
sonar.tests=src/test/java

# Encoding
sonar.sourceEncoding=UTF-8

# Java version
sonar.java.source=17

# Exclusions from Sonar analysis (generated code, etc)
sonar.exclusions=**/generated-sources/**, **/target/**
