export const TRIAGE_COPY_KEYS = {
  pageTitle: 'agentTriage.pageTitle',
  greeting: 'agentTriage.greeting',
  greetingDescription: 'agentTriage.greetingDescription',
  inputPlaceholder: 'agentTriage.inputPlaceholder',
  sendButton: 'agentTriage.sendButton',
  steps: {
    symptoms: 'agentTriage.steps.symptoms',
    history: 'agentTriage.steps.history',
    details: 'agentTriage.steps.details',
    review: 'agentTriage.steps.review',
  },
  orbState: {
    collecting: 'agentTriage.orbState.collecting',
    analyzing: 'agentTriage.orbState.analyzing',
    ready: 'agentTriage.orbState.ready',
    emergency: 'agentTriage.orbState.emergency',
  },
  quickReplies: [
    'agentTriage.quickReplies.headache',
    'agentTriage.quickReplies.fever',
    'agentTriage.quickReplies.cough',
    'agentTriage.quickReplies.breathing',
    'agentTriage.quickReplies.chestPain',
    'agentTriage.quickReplies.insomnia',
  ],
} as const

export const TRIAGE_FALLBACK_COPY = {
  pageTitle: 'AI Triage',
  greetingDescription: 'Describe your symptoms so CareTriage can guide the next step.',
  greeting: 'Hello, I am the CareTriage AI Assistant. Could you please describe the symptoms you are experiencing?',
  inputPlaceholder: 'Describe your symptoms here...',
  send: 'Send',
  retry: 'Retry',
  errorFallback: 'Unable to analyze your response. Please try again.',
  emergencyAction: 'Emergency mode is active.',
  composerHint: 'Start with where it hurts, when it began, and how severe it feels from 1 to 10.',
  safetyNote: 'AI supports initial triage only. If you have chest pain, trouble breathing, fainting, heavy bleeding, or confusion, call emergency services now.',
  historyTitle: 'History',
  historyEmpty: 'Your symptom notes will appear here after you send them.',
  currentSession: 'Current session',
  historyLoading: 'Loading sessions...',
  historyError: 'Unable to load sessions.',
  steps: {
    symptoms: 'Symptoms',
    history: 'Medical history',
    details: 'Details',
    review: 'Review',
  },
  orbState: {
    collecting: 'Collecting symptoms',
    analyzing: 'Analyzing response',
    ready: 'Ready for next step',
    emergency: 'Emergency detected',
  },
  quickReplies: {
    headache: 'Headache',
    fever: 'Fever',
    cough: 'Cough',
    breathing: 'Breathing issue',
    chestPain: 'Chest pain',
    insomnia: 'Insomnia',
  },
  promptCards: [
    {
      title: 'Where do you feel it?',
      body: 'Tell us the location and whether it spreads anywhere.',
      prompt: 'I feel pain or discomfort in ',
    },
    {
      title: 'When did it start?',
      body: 'Mention duration, sudden changes, and what makes it better or worse.',
      prompt: 'It started ',
    },
    {
      title: 'How severe is it?',
      body: 'Use a 1 to 10 scale and include fever, nausea, dizziness, or fatigue.',
      prompt: 'The severity is ',
    },
    {
      title: 'Any urgent signs?',
      body: 'Chest pain, trouble breathing, fainting, severe bleeding, or confusion matter most.',
      prompt: 'I also noticed ',
    },
  ],
} as const

export const TRIAGE_FALLBACK_COPY_VI = {
  pageTitle: 'Sơ chẩn AI',
  greetingDescription: 'Mô tả triệu chứng để CareTriage hướng dẫn bước tiếp theo phù hợp.',
  greeting: 'Chào bạn, tôi là Trợ lý AI CareTriage. Vui lòng mô tả triệu chứng bạn đang gặp phải.',
  inputPlaceholder: 'Mô tả triệu chứng của bạn tại đây...',
  send: 'Gửi',
  retry: 'Thử lại',
  errorFallback: 'Không thể phân tích phản hồi. Vui lòng thử lại.',
  emergencyAction: 'Chế độ cấp cứu đang bật.',
  composerHint: 'Bắt đầu bằng vị trí đau, thời điểm xuất hiện và mức độ từ 1 đến 10.',
  safetyNote: 'AI chỉ hỗ trợ phân loại ban đầu. Nếu có đau ngực, khó thở, ngất, chảy máu nhiều hoặc lú lẫn, hãy gọi cấp cứu ngay.',
  historyTitle: 'Lịch sử',
  historyEmpty: 'Chưa có phiên sơ chẩn nào.',
  currentSession: 'Phiên hiện tại',
  historyLoading: 'Đang tải phiên...',
  historyError: 'Không thể tải lịch sử phiên.',
  steps: {
    symptoms: 'Triệu chứng',
    history: 'Tiền sử y tế',
    details: 'Thông tin bổ sung',
    review: 'Xem lại',
  },
  orbState: {
    collecting: 'Đang thu thập triệu chứng',
    analyzing: 'Đang phân tích',
    ready: 'Sẵn sàng cho bước tiếp theo',
    emergency: 'Phát hiện cấp cứu',
  },
  quickReplies: {
    headache: 'Đau đầu',
    fever: 'Sốt',
    cough: 'Ho',
    breathing: 'Khó thở',
    chestPain: 'Đau ngực',
    insomnia: 'Mất ngủ',
  },
  promptCards: [
    {
      title: 'Bạn đau ở đâu?',
      body: 'Mô tả vị trí đau và có lan sang vùng nào khác không.',
      prompt: 'Tôi cảm thấy đau hoặc khó chịu ở ',
    },
    {
      title: 'Bắt đầu khi nào?',
      body: 'Cho biết thời gian, thay đổi đột ngột, và điều làm nặng hoặc giảm.',
      prompt: 'Triệu chứng bắt đầu từ ',
    },
    {
      title: 'Mức độ thế nào?',
      body: 'Dùng thang điểm 1 đến 10 và nêu kèm sốt, chóng mặt, buồn nôn, mệt mỏi.',
      prompt: 'Mức độ nghiêm trọng là ',
    },
    {
      title: 'Có dấu hiệu nguy hiểm?',
      body: 'Đau ngực, khó thở, ngất, chảy máu nhiều, hoặc rối loạn ý thức cần ưu tiên.',
      prompt: 'Tôi cũng nhận thấy ',
    },
  ],
} as const
